printWidth: 100
tabWidth: 4
semi: true
singleQuote: true
endOfLine: 'lf'
trailingComma: 'es5'
plugins:
    - '@trivago/prettier-plugin-sort-imports'
importOrderSeparation: true
importOrder:
    # react-related packages
    - '^react.*$'
    # aliased paths
    - "^@.*(?<!\\.scss)$"
    # relative paths
    - "^\\.{1,2}/.*(?<!\\.scss)$"
    # styles
    - "^.*\\.scss$"
